POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "NewAcc4",
  "password": "12345678"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "NewAcc5",
  "password": "12345678"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3ZmEzZjM3ZTZjMzM2Y2NmZTdhODQiLCJpYXQiOjE2ODM0ODcyOTV9.hEfjAgx6JgG_iDA28n_LgHOT_LCumTA_GP0vhjFmZVg

{
  "title": "Reac23t",
  "description": "React",
  "url": "react.com",
  "status": "TO LEARN"
}

###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU3ZmEzZjM3ZTZjMzM2Y2NmZTdhODQiLCJpYXQiOjE2ODM0ODcyOTV9.hEfjAgx6JgG_iDA28n_LgHOT_LCumTA_GP0vhjFmZVg

###

PUT http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTcwMTk3ODF9.ri-nHdgZc1VQTocFLfMgF4_PhFf2TeUVqXLd8tpOkeA

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTcwMTk3ODF9.ri-nHdgZc1VQTocFLfMgF4_PhFf2TeUVqXLd8tpOkeA
